# Generated by Django 3.2.6 on 2021-08-17 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insurance_Product', models.CharField(blank=True, choices=[('P1', 'COVID-19 PROTECTION'), ('P2', 'HEALTH INSURANCE FOR SELF AND DEPENDENTS'), ('P3', 'HEALTH INSURANCE FOR PARENTS'), ('P4', 'HEALTH INSURANCE FOR EMPLOYEES')], max_length=100, null=True)),
                ('First_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('Income_Group', models.CharField(blank=True, choices=[('Low Income', 'Low Income'), ('Middle Income', 'Middle Income'), ('High Income', 'High Income')], max_length=100, null=True)),
                ('Morbidity_History', models.CharField(blank=True, choices=[('D1', 'Cardiovascular Disease'), ('D2', 'Diabetes'), ('D3', 'Tumor'), ('D4', 'Obesity'), ('D5', 'Hyperlipidemia'), ('D5', 'Respiratory Disease')], max_length=100, null=True)),
                ('Lifestyle_Variables', models.CharField(blank=True, choices=[('D1', 'Unhealthy Eating Habit'), ('D2', 'Smoking and Drinking'), ('D3', 'Burning Midnight Oil'), ('D4', 'Emotionally unstable'), ('D5', 'Regular Excercise'), ('D5', 'Practice Meditation')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insurance_Product', models.CharField(blank=True, choices=[('P1', 'COVID-19 PROTECTION'), ('P2', 'HEALTH INSURANCE FOR SELF AND DEPENDENTS'), ('P3', 'HEALTH INSURANCE FOR PARENTS'), ('P4', 'HEALTH INSURANCE FOR EMPLOYEES')], max_length=100, null=True)),
                ('First_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Contact_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Residential_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Zip_Code', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_of_Birth_mm_dd_yyyy', models.DateField(blank=True, max_length=255, null=True)),
                ('Your_Age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True)),
                ('SSN_or_TAX_ID', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Income_Group', models.CharField(blank=True, choices=[('Low Income', 'Low Income'), ('Middle Income', 'Middle Income'), ('High Income', 'High Income')], max_length=100, null=True)),
                ('Income', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Morbidity_History', models.CharField(blank=True, choices=[('D1', 'Cardiovascular Disease'), ('D2', 'Diabetes'), ('D3', 'Tumor'), ('D4', 'Obesity'), ('D5', 'Hyperlipidemia'), ('D5', 'Respiratory Disease')], max_length=100, null=True)),
                ('Lifestyle_Variables', models.CharField(blank=True, choices=[('D1', 'Unhealthy Eating Habit'), ('D2', 'Smoking and Drinking'), ('D3', 'Burning Midnight Oil'), ('D4', 'Emotionally unstable'), ('D5', 'Regular Excercise'), ('D5', 'Practice Meditation')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fkey_Do_Not_Change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.data')),
            ],
        ),
    ]
